# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 529)
        Form.setStyleSheet("QWidget {\n"
                           " background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 184, 255), stop:1 rgba(255, 79, 255, 255))\n"
                           "}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(410, 470, 151, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "  background-color: #0d6efd;\n"
                                      "  color: #fff;\n"
                                      "  font-weight: 600;\n"
                                      "  border-radius: 8px;\n"
                                      "  border: 1px solid #0d6efd;\n"
                                      "  padding: 5px 15px;\n"
                                      "  margin-top: 10px;\n"
                                      "  outline: 0px;\n"
                                      "}\n"
                                      "QPushButton:hover,\n"
                                      "QPushButton:focus {\n"
                                      "  background-color: #0b5ed7;\n"
                                      "  border: 3px solid #9ac3fe;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
